# Generated by Django 4.1.5 on 2023-01-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_course_certificate_course_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Certificate',
            field=models.BooleanField(max_length=100, null=True),
        ),
    ]
